name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd the-internet-ui && docker build . --file Dockerfile -t the-internet && docker image ls

    - name: Build container with app
      run: docker run -p 5000:5000 the-internet
