# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_EMAIL: ${{ secrets.MY_EMAIL }}
  APP_NAME: the-internet-app-e2e-tests

jobs:

  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku login credentials
        run: |
           docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
           echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
           heroku container:login

      - name: Build the Docker image
        run: cd the-internet-ui && docker build --file Dockerfile --no-cache --tag $APP_NAME . && docker images

      - name: Deploy on heroku
        run: |
          heroku container:push -a $APP_NAME web
          heroku container:release -a $APP_NAME web

      - name: Check if server is running
        run: |
          curl -I http://172.17.0.1:5000/add_remove_elements/ | grep HTTP/ | awk '{print $2}' | echo "Status: $(cat)"          
          echo "Server is up and running"   
          sudo docker inspect the-internet-app    

  build-job:
    needs: container-job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - run: google-chrome-stable --version
      - name: Build tests with Maven
        run: mvn -B package --file selenium-tests/pom.xml test
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_E2ETESTS}}